[package]
name = "opensearch-testcontainer"
description = "Testcontainer for OpenSearch"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true
keywords = [
    "docker",
    "testcontainers",
    "testcontainer",
    "opensearch",
    "integration-test",
]
readme.workspace = true

[dependencies]
testcontainers = "0.16.7"

[dev-dependencies]
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
